-- SQLite model: ticket and assignment fact tables have surrogate integer keys; ticket_id is the durable business key.
CREATE TABLE stg_tickets(ticket_id TEXT PRIMARY KEY,created_at TEXT NOT NULL,first_response_at TEXT NOT NULL,resolved_at TEXT,priority TEXT NOT NULL,category TEXT NOT NULL,initial_queue TEXT NOT NULL,response_target_hours REAL NOT NULL,resolution_target_hours REAL NOT NULL,reopened INTEGER NOT NULL,state TEXT NOT NULL);
CREATE TABLE stg_assignment_history(ticket_id TEXT NOT NULL,sequence INTEGER NOT NULL,queue TEXT NOT NULL,assigned_at TEXT NOT NULL,unassigned_at TEXT,PRIMARY KEY(ticket_id,sequence),FOREIGN KEY(ticket_id) REFERENCES stg_tickets(ticket_id));
CREATE TABLE dim_date(date_key INTEGER PRIMARY KEY,calendar_date TEXT UNIQUE NOT NULL,calendar_year INTEGER NOT NULL,calendar_month INTEGER NOT NULL,year_month TEXT NOT NULL);
CREATE TABLE dim_priority(priority_key INTEGER PRIMARY KEY,priority_code TEXT UNIQUE NOT NULL);
CREATE TABLE dim_category(category_key INTEGER PRIMARY KEY,category_name TEXT UNIQUE NOT NULL);
CREATE TABLE dim_queue(queue_key INTEGER PRIMARY KEY,queue_name TEXT UNIQUE NOT NULL);
CREATE TABLE fact_ticket_sla(ticket_key INTEGER PRIMARY KEY,ticket_id TEXT UNIQUE NOT NULL,created_date_key INTEGER NOT NULL,resolved_date_key INTEGER,priority_key INTEGER NOT NULL,category_key INTEGER NOT NULL,initial_queue_key INTEGER NOT NULL,created_at TEXT NOT NULL,first_response_at TEXT NOT NULL,resolved_at TEXT,response_target_hours REAL NOT NULL,resolution_target_hours REAL NOT NULL,reopened INTEGER NOT NULL,state TEXT NOT NULL,mtta_hours REAL NOT NULL,mttr_hours REAL NOT NULL,age_hours REAL NOT NULL,response_breached INTEGER NOT NULL,resolution_breached INTEGER NOT NULL,sla_breached INTEGER NOT NULL,transfer_count INTEGER NOT NULL,risk_score REAL NOT NULL,risk_band TEXT NOT NULL,FOREIGN KEY(created_date_key) REFERENCES dim_date(date_key),FOREIGN KEY(resolved_date_key) REFERENCES dim_date(date_key),FOREIGN KEY(priority_key) REFERENCES dim_priority(priority_key),FOREIGN KEY(category_key) REFERENCES dim_category(category_key),FOREIGN KEY(initial_queue_key) REFERENCES dim_queue(queue_key));
CREATE TABLE fact_assignment(assignment_key INTEGER PRIMARY KEY,ticket_key INTEGER NOT NULL,queue_key INTEGER NOT NULL,event_sequence INTEGER NOT NULL,assigned_at TEXT NOT NULL,unassigned_at TEXT,UNIQUE(ticket_key,event_sequence),FOREIGN KEY(ticket_key) REFERENCES fact_ticket_sla(ticket_key),FOREIGN KEY(queue_key) REFERENCES dim_queue(queue_key));
